# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Daily checks for updates in Github Actions (CI/CD workflows)
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    groups:
      ci-cd:
        patterns:
          - '*' # Group all updates together

  # Daily checks for npm package updates in CI-CD scripts
  - package-ecosystem: 'npm'
    directory: '/.github/scripts'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    groups:
      ci-cd:
        patterns:
          - '*' # Group all updates together

  # Daily checks for pip package updates in build system scripts
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    groups:
      build-system:
        patterns:
          - '*' # Group all updates together

  # Daily checks for npm package updates in frontend
  - package-ecosystem: 'npm'
    directory: '/frontend'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
    groups:
      frontend:
        patterns:
          - '*' # Group all updates together
