name: cdn-bump-version
description: Uploads version file to CDN
inputs:
  cf-bucket:
    description: Name of the S3 bucket
    required: true
  version:
    description: 'Version of the release'
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true

env:
  S3_BUCKET_NAME: ${{ inputs.cf-bucket }}
  S3_ACCOUNT_ID: ${{ vars.S3_ACCOUNT_ID }}
  S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}

runs:
  using: composite
  steps:
    - name: Upload version file
      shell: bash
      run: echo "${{ inputs.version }}" | node ./.github/scripts/dist/s3-upload.js stdin "version-${{ inputs.release-channel }}.txt" "text/plain"
