name: cdn-upload-version-info
description: Uploads version specific info to CDN
inputs:
  s3-bucket:
    description: Name of the S3 bucket
    required: true
  s3-account-id:
    description: S3 account ID
    required: true
  s3-access-key-id:
    description: S3 access key ID
    required: true
  s3-secret-access-key:
    description: S3 secret access key
    required: true
  fw-version:
    description: Firmware version
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true
  boards:
    description: 'List of boards, separated by newlines'
    required: true

env:
  S3_BUCKET_NAME: ${{ inputs.s3-bucket }}
  S3_ACCOUNT_ID: ${{ inputs.s3-account-id }}
  S3_ACCESS_KEY_ID: ${{ inputs.s3-access-key-id }}
  S3_SECRET_ACCESS_KEY: ${{ inputs.s3-secret-access-key }}

runs:
  using: composite
  steps:
    - name: Create boards.txt
      shell: bash
      run: echo -e '${{ inputs.boards }}' | node ./.github/scripts/dist/s3-upload.js stdin "boards.txt" "text/plain"
