name: cdn-upload-version-info
description: Uploads version specific info to CDN
inputs:
  cf-bucket:
    description: Name of the S3 bucket
    required: true
  fw-version:
    description: Firmware version
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true
  boards:
    description: 'List of boards, separated by newlines'
    required: true

env:
  S3_BUCKET_NAME: ${{ inputs.cf-bucket }}
  S3_ACCOUNT_ID: ${{ vars.S3_ACCOUNT_ID }}
  S3_ACCESS_KEY_ID: ${{ vars.S3_ACCESS_KEY_ID }}
  S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}

runs:
  using: composite
  steps:
    - name: Create boards.txt
      shell: bash
      run: echo -e '${{ inputs.boards }}' | node ./.github/scripts/dist/s3-upload.js stdin "boards.txt" "text/plain"
